// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWG2cX6L0O00CfUXiQ2jUJ5ecw1kMrNHs',
    appId: '1:81098138212:web:3f151f7f43750df78df571',
    messagingSenderId: '81098138212',
    projectId: 'aeapp-e9bab',
    authDomain: 'aeapp-e9bab.firebaseapp.com',
    storageBucket: 'aeapp-e9bab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBezfoxgSQ0esvLuJ0SwYSm0XX9KGiDBeQ',
    appId: '1:81098138212:android:441ccd89143438c18df571',
    messagingSenderId: '81098138212',
    projectId: 'aeapp-e9bab',
    storageBucket: 'aeapp-e9bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQRiM5OpLcMUMaUub6xN2F5Im1xYDJYE',
    appId: '1:81098138212:ios:efaaf6e4541d67aa8df571',
    messagingSenderId: '81098138212',
    projectId: 'aeapp-e9bab',
    storageBucket: 'aeapp-e9bab.appspot.com',
    iosBundleId: 'com.example.aeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQRiM5OpLcMUMaUub6xN2F5Im1xYDJYE',
    appId: '1:81098138212:ios:999a78b91e53f6f18df571',
    messagingSenderId: '81098138212',
    projectId: 'aeapp-e9bab',
    storageBucket: 'aeapp-e9bab.appspot.com',
    iosBundleId: 'com.example.aeapp.RunnerTests',
  );
}
